spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    template:
      default-topic: wiki-demo
    producer:
      bootstrap-servers: cluster.playground.cdkt.io:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security:
          protocol: SASL_SSL
        sasl:
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="5LNIJNevEcJCu0a3BQAmkj" password="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguY29uZHVrdG9yLmlvIiwic291cmNlQXBwbGljYXRpb24iOiJhZG1pbiIsInVzZXJNYWlsIjpudWxsLCJwYXlsb2FkIjp7InZhbGlkRm9yVXNlcm5hbWUiOiI1TE5JSk5ldkVjSkN1MGEzQlFBbWtqIiwib3JnYW5pemF0aW9uSWQiOjc0NjcyLCJ1c2VySWQiOjg2Mzc1LCJmb3JFeHBpcmF0aW9uQ2hlY2siOiI1YjE2ZGE3MC00ZjczLTQ1N2UtODQ3YS1hNWNlM2ZmN2FhYTYifX0.DlQHjg9qLyarc7evCd12S9SbLH9C4doviEpFBpKLdcU";
          mechanism: PLAIN

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: wiki-demo
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094

